using System.Numerics;
using Content.Client.UserInterface.Systems.Actions.Controls;
using Content.Shared.CCVar;
using Content.Shared.Input;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Timing;

namespace Content.Client.UserInterface.Systems.Actions.Widgets;

[GenerateTypedNameReferences]
public sealed partial class ActionsBar : UIWidget
{
    /// <summary>
    /// Side of a single action slot.
    /// </summary>
    private const float SlotSize = 64f;

    /// <summary>
    /// GridContainer's default gap between slots. Needed to turn a row count into a height budget.
    /// </summary>
    private const float SlotSeparation = 4f;

    /// <summary>
    /// Floor for the vertical bar's height budget. The grid falls back to a single row once fewer than
    /// two slots fit, so keep enough room that a cramped window still gets a column.
    /// </summary>
    private const float MinGridHeight = SlotSize * 3f;

    /// <summary>
    /// Screen space kept free below the vertical bar so it does not run into the bottom left inventory.
    /// </summary>
    private const float VerticalBottomMargin = 128f;

    /// <summary>
    /// Upstream clamp for the single row layout. Keeps the bar from widening the HUD corner it sits in.
    /// </summary>
    private static readonly Vector2 HorizontalMaxSize = new(SlotSize, 9999f);

    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    private bool? _vertical;
    private float _gridHeight;

    public ActionsBar()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var keys = ContentKeyFunctions.GetHotbarBoundKeys();
        for (var index = 1; index < keys.Length; index++)
            ActionsContainer.Children.Add(MakeButton(index));
        ActionsContainer.Children.Add(MakeButton(0));

        ActionButton MakeButton(int index)
        {
            var boundKey = keys[index];
            var button = new ActionButton(_entity);
            button.KeyBind = boundKey;
            button.Label.Text = index.ToString();
            return button;
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var vertical = _cfg.GetCVar(CCVars.HudActionBarVertical);
        if (_vertical != vertical)
        {
            _vertical = vertical;
            _gridHeight = 0f;

            if (vertical)
            {
                // A wrapped bar is wider than one slot, so the horizontal clamp has to come off.
                ActionsContainer.MaxSize = new Vector2(float.PositiveInfinity, float.PositiveInfinity);
            }
            else
            {
                ActionsContainer.MaxSize = HorizontalMaxSize;
                ActionsContainer.Rows = 1;
            }
        }

        if (vertical)
            UpdateGridHeight();
    }

    /// <summary>
    /// Caps the grid at the height actually left below the bar, which makes the container lay the slots
    /// out top to bottom and wrap the overflow into a new column instead of running off screen.
    /// </summary>
    private void UpdateGridHeight()
    {
        var available = MathF.Max(
            UserInterfaceManager.RootControl.Size.Y - GlobalPosition.Y - VerticalBottomMargin,
            MinGridHeight);

        // A configured column length wins, as long as it still fits on screen.
        var rows = _cfg.GetCVar(CCVars.HudActionBarRows);
        if (rows > 0)
            available = MathF.Min(available, rows * (SlotSize + SlotSeparation) - SlotSeparation);

        // MaxGridHeight invalidates measure, so only touch it when the space actually changed.
        if (MathF.Abs(available - _gridHeight) < 1f)
            return;

        _gridHeight = available;
        ActionsContainer.MaxGridHeight = available;
    }
}
