using System.Globalization;
using Content.Client.UserInterface.Controls;
using Content.Shared._Crescent.Taxation;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Crescent.Taxation;

[GenerateTypedNameReferences]
public sealed partial class TreasuryConsoleWindow : FancyWindow
{
    /// <summary>Raised with the amount of credits to withdraw.</summary>
    public event Action<int>? OnWithdraw;

    private int _remaining;

    public TreasuryConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("treasury-console-title");

        WithdrawButton.OnPressed += _ =>
        {
            if (int.TryParse(AmountEdit.Text?.Trim(), NumberStyles.Integer, CultureInfo.InvariantCulture, out var amount) && amount > 0)
                OnWithdraw?.Invoke(amount);
        };

        // Asks for the player's own remaining allowance, not the whole balance. Asking for the balance
        // got silently clamped to the cap, so the button reported a smaller figure than the one above
        // it with nothing to explain the gap.
        WithdrawAllButton.OnPressed += _ =>
        {
            if (_remaining > 0)
                OnWithdraw?.Invoke(_remaining);
        };
    }

    public void UpdateState(TreasuryConsoleState state)
    {
        _remaining = state.Remaining;

        BalanceLabel.Text = Loc.GetString("treasury-console-balance", ("balance", state.Balance));

        RemainingLabel.Text = Loc.GetString("treasury-console-remaining",
            ("remaining", state.Remaining), ("percent", state.CapPercent));
        RemainingLabel.Modulate = state.Remaining > 0 ? Color.LightGray : Color.DarkOrange;

        if (state.AlarmActive)
        {
            AlarmLabel.Text = Loc.GetString("treasury-console-alarm");
            AlarmLabel.Modulate = Color.Red;
        }
        else
        {
            AlarmLabel.Text = string.Empty;
        }

        StatusLabel.Text = Loc.GetString(state.Authorized
            ? "treasury-console-authorized"
            : "treasury-console-unauthorized");
        StatusLabel.Modulate = state.Authorized ? Color.LightGreen : Color.OrangeRed;

        AmountEdit.Editable = state.Authorized;
        WithdrawButton.Disabled = !state.Authorized;
        WithdrawAllButton.Disabled = !state.Authorized;
    }
}
