using Content.Client.Computer;
using Content.Client.PointCannons;
using Content.Client.UserInterface.Controls;
using Content.Shared.Shuttles.BUIStates;
using Content.Shared.PointCannons;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Content.Client.Shuttles.UI;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface;

namespace Content.Client._Crescent.PointCannons;

[GenerateTypedNameReferences]
public sealed partial class TargetingConsoleWindow : FancyWindow, IComputerWindow<ShuttleBoundUserInterfaceState>
{
    public ShuttleNavControl Radar => NavRadar;
    public Action<string>? OnCannonGroupChange;
    public Action? OnServerRefresh;

    public TargetingConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        RefreshButton.OnPressed += _ => OnServerRefresh?.Invoke();
    }

    public void UpdateState(TargetingConsoleBoundUserInterfaceState state)
    {
        NavRadar.UpdateState(state.NavState);
        NavRadar.UpdateState(state.IFFState);

        if (state.CannonGroups != null)
            UpdateGroupSelector(state.CannonGroups);
    }

    public void UpdateGroupSelector(List<string> groups)
    {
        CannonGroupSelectorBox.DisposeAllChildren();

        foreach (string groupName in groups)
        {
            Button groupButton = new();
            groupButton.Text = string.Concat(char.ToUpper(groupName[0]), groupName.Substring(1)); //capitalized name
            groupButton.OnPressed += (_) =>
            {
                OnCannonGroupChange?.Invoke(groupName);
            };
            CannonGroupSelectorBox.AddChild(groupButton);
        }
    }

    public void UpdateAmmoStatus(List<(int, int)> values)
    {
        // This runs on the UI tick, so reuse the bars instead of rebuilding them every time.
        while (AmmoStatusBox.ChildCount > values.Count)
            AmmoStatusBox.GetChild(AmmoStatusBox.ChildCount - 1).Dispose();

        while (AmmoStatusBox.ChildCount < values.Count)
            AmmoStatusBox.AddChild(new AmmoBar());

        for (var i = 0; i < values.Count; i++)
        {
            var (value, max) = values[i];
            if (AmmoStatusBox.GetChild(i) is not AmmoBar bar)
                continue;

            //funny, but it's important that max value is set before value
            //or it will get clamped to the default max of 100
            bar.MaxValue = max;
            bar.Value = value;
        }
    }
}
