using Content.Shared._EE.Contractors.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._EE.Contractors.UI;

[GenerateTypedNameReferences]
public sealed partial class PassportWindow : DefaultWindow
{
    public event Action<PassportSaveMessage>? SaveRequested;

    public PassportWindow()
    {
        RobustXamlLoader.Load(this);
        SaveButton.OnPressed += OnSavePressed;
    }

    public void UpdateState(PassportBoundUserInterfaceState state)
    {
        FullNameEdit.Text = state.FullName;
        AgeEdit.Text = state.Age.ToString();
        SpeciesEdit.Text = state.Species;
        SexEdit.Text = state.Sex;
        HeightEdit.Text = state.HeightCm.ToString();
        SkinColorEdit.Text = state.SkinColor;
        EyeColorEdit.Text = state.EyeColor;
        NationalityEdit.Text = state.Nationality;
        ReligionEdit.Text = state.Religion;
        PassportIdEdit.Text = state.PassportId;
        IssueYearEdit.Text = state.IssueYear.ToString();
        ExpirationYearEdit.Text = state.ExpirationYear.ToString();
        FormStatusLabel.Text = Loc.GetString(state.Tampered
            ? "passport-ui-tampered"
            : state.IsValid
                ? "passport-ui-valid"
                : "passport-ui-invalid");
    }

    private void OnSavePressed(BaseButton.ButtonEventArgs args)
    {
        if (!int.TryParse(AgeEdit.Text, out var age)
            || !int.TryParse(HeightEdit.Text, out var heightCm)
            || !int.TryParse(IssueYearEdit.Text, out var issueYear)
            || !int.TryParse(ExpirationYearEdit.Text, out var expirationYear))
        {
            FormStatusLabel.Text = Loc.GetString("passport-ui-number-error");
            return;
        }

        SaveRequested?.Invoke(new PassportSaveMessage(
            FullNameEdit.Text,
            age,
            SpeciesEdit.Text,
            SexEdit.Text,
            heightCm,
            SkinColorEdit.Text,
            EyeColorEdit.Text,
            NationalityEdit.Text,
            ReligionEdit.Text,
            PassportIdEdit.Text,
            issueYear,
            expirationYear));
    }
}
