- type: department
  id: Independents
  description: department-Independents-description
  color: "#374b4e"
  weight: 10
  roles:
  - MarshalCMM
  - DeputyMarshalCMM
  - MinutemanCMM
  - Spacer
  editorHidden: false
