using Content.Shared._Crescent.PassportControl;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._Crescent.PassportControl;

[GenerateTypedNameReferences]
public sealed partial class PassportControlWindow : DefaultWindow
{
    private static readonly Color GoodColor = Color.FromHex("#62d474");
    private static readonly Color WarningColor = Color.FromHex("#e6bd5c");
    private static readonly Color BadColor = Color.FromHex("#ed6666");

    public event Action? OnReset;

    public PassportControlWindow()
    {
        RobustXamlLoader.Load(this);
        ResetButton.OnPressed += _ => OnReset?.Invoke();
    }

    public void UpdateState(PassportControlBoundUserInterfaceState state)
    {
        UpdateConnection(PassportConnectionLabel, state.PassportReaderConnected,
            "passport-control-passport-reader");
        UpdateConnection(FingerprintConnectionLabel, state.FingerprintScannerConnected,
            "passport-control-fingerprint-reader");

        PassportLabel.Text = state.HasPassport
            ? Loc.GetString("passport-control-passport-identity",
                ("name", state.PassportName),
                ("id", state.PassportId))
            : Loc.GetString("passport-control-passport-none");

        DocumentLabel.Text = GetDocumentText(state);
        FingerprintLabel.Text = GetFingerprintText(state);
        ResultLabel.Text = Loc.GetString(GetStatusKey(state.Status));
        ResultLabel.FontColorOverride = GetStatusColor(state.Status);
    }

    private static void UpdateConnection(Label label, bool connected, string deviceKey)
    {
        label.Text = Loc.GetString("passport-control-device-connection",
            ("device", Loc.GetString(deviceKey)),
            ("status", Loc.GetString(connected
                ? "passport-control-connected"
                : "passport-control-disconnected")));
        label.FontColorOverride = connected ? GoodColor : BadColor;
    }

    private static string GetDocumentText(PassportControlBoundUserInterfaceState state)
    {
        if (!state.HasPassport)
            return Loc.GetString("passport-control-document-not-scanned");

        if (state.Status == PassportControlStatus.WaitingForFingerprint)
            return Loc.GetString("passport-control-document-pending");

        return Loc.GetString(state.PassportValid
            ? "passport-control-document-valid"
            : "passport-control-document-invalid");
    }

    private static string GetFingerprintText(PassportControlBoundUserInterfaceState state)
    {
        if (state.Status == PassportControlStatus.BiometricUnavailable)
            return Loc.GetString("passport-control-fingerprint-unavailable");

        return state.FingerprintMatched switch
        {
            true => Loc.GetString("passport-control-fingerprint-match"),
            false => Loc.GetString("passport-control-fingerprint-mismatch"),
            null => Loc.GetString("passport-control-fingerprint-pending"),
        };
    }

    private static string GetStatusKey(PassportControlStatus status)
    {
        return status switch
        {
            PassportControlStatus.Idle => "passport-control-status-idle",
            PassportControlStatus.WaitingForFingerprint => "passport-control-status-waiting",
            PassportControlStatus.Verified => "passport-control-status-verified",
            PassportControlStatus.PassportInvalid => "passport-control-status-passport-invalid",
            PassportControlStatus.FingerprintMismatch => "passport-control-status-fingerprint-mismatch",
            PassportControlStatus.BiometricUnavailable => "passport-control-status-biometric-unavailable",
            _ => "passport-control-status-idle",
        };
    }

    private static Color GetStatusColor(PassportControlStatus status)
    {
        return status switch
        {
            PassportControlStatus.Verified => GoodColor,
            PassportControlStatus.Idle or PassportControlStatus.WaitingForFingerprint => WarningColor,
            _ => BadColor,
        };
    }
}
